models:
  esm2_t6_8M:
    path: "facebook/esm2_t6_8M_UR50D"

  esm2_t12_35M:
    path: "facebook/esm2_t12_35M_UR50D"

  esm2_t30_150M:
    path: "facebook/esm2_t30_150M_UR50D"

  esm2_t33_650M:
    path: "facebook/esm2_t33_650M_UR50D"

  # Legacy ESM1 models (for backward compatibility)
  esm1b:
    path: "facebook/esm1b_t33_650M_UR50S"

  esm1v1:
    path: "facebook/esm1v_t33_650M_UR90S_1"

  esm1v2:
    path: "facebook/esm1v_t33_650M_UR90S_2"

  esm1v3:
    path: "facebook/esm1v_t33_650M_UR90S_3"

  esm1v4:
    path: "facebook/esm1v_t33_650M_UR90S_4"

  esm1v5:
    path: "facebook/esm1v_t33_650M_UR90S_5"

  # Fine-tuned ESM2 models
  esm2-dgoa-650M:
    path: "/eagle/projects/FoundEpidem/xlian/checkpoints/dgoa-esm/dgoa-runs-650M/checkpoint-2210"

  esm2-dgoa-150M:
    path: "/eagle/projects/FoundEpidem/xlian/checkpoints/dgoa-esm/dgoa-runs-150M/checkpoint-2210"


model_sets:
  esm2_original_debug:
      - esm2_t6_8M
      - esm2_t33_650M

  esm2_finetuned:
    - esm2-dgoa-650M
    - esm2-dgoa-150M

  esm2_mixed_original_and_finetuned:
    - esm2_t33_650M
    - esm2-dgoa-650M
    - esm2_t30_150M
    - esm2-dgoa-150M

  # Legacy ESM1 model sets (for backward compatibility)
  esm1_original:
    - esm1b
    - esm1v1
    - esm1v2
    - esm1v3
    - esm1v4
    - esm1v5

  original_esm:
    - esm2_t33_650M
    - esm2_t30_150M